version: '3'
services:
  # The Backed Server
  server:
    image: "963933760463.dkr.ecr.us-east-1.amazonaws.com/prod-redkite-backend"
    # build:
    #   context: ./
    #   dockerfile: local-server.dockerfile
    ports:
      - "3333:3333" 
    volumes:
      - /home/ubuntu/uploaded:/code/tmp/uploads
    links:
      - kue
      - redis
      # - mysql
  server2:
    image: "963933760463.dkr.ecr.us-east-1.amazonaws.com/prod-redkite-backend"
    # build:
    #   context: ./
    #   dockerfile: local-server.dockerfile
    ports:
      - "3334:3333" 
    volumes:
      - /home/ubuntu/uploaded:/code/tmp/uploads
    links:
      - kue
      - redis
  server3:
    image: "963933760463.dkr.ecr.us-east-1.amazonaws.com/prod-redkite-backend"
    # build:
    #   context: ./
    #   dockerfile: local-server.dockerfile
    ports:
      - "3335:3333" 
    volumes:
      - /home/ubuntu/uploaded:/code/tmp/uploads
    links:
      - kue
      - redis
  # The Kue
  kue:
    image: "963933760463.dkr.ecr.us-east-1.amazonaws.com/prod-redkite-kue"
    # build:
    #   context: ./
    #   dockerfile: local-kue.dockerfile
    ports:
      - "3002:3001" 
    volumes:
      - backend-kue:/app
    links:
      - redis
      # - mysql

  # # Mysql Database
  # mysql:
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Sotatek2021
  #     - MYSQL_DATABASE=adonis
  #     - MYSQL_USER=adonis
  #     - MYSQL_PASSWORD=adonis#2021
  #   volumes:
  #     - backend-mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   restart: always

   # Redis Database
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  backend-kue:
  backend-mysql:
  backend-redis:
