version: '3'
services:
  # The Kue
#  kue:
#    image: "963933760463.dkr.ecr.us-east-1.amazonaws.com/prod-redkite-kue"
#    # build:
#    #   context: ./
#    #   dockerfile: local-kue.dockerfile
#    ports:
#      - "3002:3001"
#    volumes:
#      - backend-kue:/app
#    links:
#      - redis
#      # - mysql

  # # Mysql Database
  mysql:
   image: mysql:5.7
   command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   environment:
     - MYSQL_ROOT_PASSWORD=Sotatek2021
     - MYSQL_DATABASE=adonis
     - MYSQL_USER=adonis
     - MYSQL_PASSWORD=adonis#2021
   volumes:
     - backend-mysql:/var/lib/mysql
   ports:
     - "3306:3306"
   restart: always

   # Redis Database
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  backend-mysql:
  backend-redis:
